// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqUntbbxmVTEcqUZZLDAtySKtp77o5J3Q',
    appId: '1:593340873232:android:1ff47d574d7c8f474ee895',
    messagingSenderId: '593340873232',
    projectId: 'chattingapp-9b5bb',
    storageBucket: 'chattingapp-9b5bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARqX8rLweOMGsQd3ONGaHqwM2yJCjGrd8',
    appId: '1:593340873232:ios:4d22abcca9ead8644ee895',
    messagingSenderId: '593340873232',
    projectId: 'chattingapp-9b5bb',
    storageBucket: 'chattingapp-9b5bb.appspot.com',
    androidClientId: '593340873232-4hifgkthch8fb9429ifcl5b27op3en4c.apps.googleusercontent.com',
    iosClientId: '593340873232-1s8uggq4h7r2n34btj17g40gld4qhf90.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
